### ISSUE TITLE
why is R-3.3.1 required (vs. 3.3.0)?

### ISSUE THREAD

**Issue by ttriche** [drsimonj/corrr#16]
Are there any 3.3.1-specific features that corrr requires?

**Comment by ttriche** [comment]
update: it doesn't appear that any negative effects occur from using 3.3.0.  

However, now I'm curious how to change the default color scheme, add a scale legend, flip the plot left-to-right, and tilt the x axis labels.  Time to fiddle with that... ASH abstract deadline looming :-)

**Comment by ttriche** [comment]
The network plot method is awesome.  Still needs a legend by default IMHO.  If I can figure this out quickly I'll send a PR.  If not... I will probably forget about it until I find this old issue via Google.

**Comment by drsimonj** [comment]
R-3.3.1 is required as this is the version that I am developing on. I'm glad to hear that there are no negative effects occurring in 3.3.0. However, I haven't run tests with 3.3.0, and I plan to continue developing in >= 3.3.1. Thus, my preference is to keep requirement of >= 3.3.1 so as to be safe rather than sorry.

Re other comments, I was tossing with the idea of offering legends and other plot adjustments, so perhaps this is a good opportunity for me to make it happen. I'll open separate issues for legend and colour scheme. Please open issues for any other features you'd like, and do submit a PR if you have quick solution. But I'll be happy to add these features soon!
