### ISSUE TITLE
to create/add a cor_df class?

### ISSUE THREAD

**Issue by duleise** [drsimonj/corrr#36]
My "correlation" is not generated by `correlate()`. It is a pairwise summary of intersection. I can convert it to `tibble`. But it is still not accepted by `rearrange` or `rplot`.
Is there any way I can add a `cor_df` class to my "correlation"? It seems that this is the only addition `correlation` does.
Thank you in advance.

**Comment by drsimonj** [comment]
Which version of corrr are you using? In the latest development version (installed from GitHub), `rplot` should work (though `rearrange` might not). This is because there was a new function added, `as_cordf()`, which will convert any **square** structure (matrix, data frame, tibble, etc) into a correlation data frame for you. Check your version and see if this works.

If still a problem, please provide a small reproducible example.

Aside, `correlate()` adds a `rowname` column in addition to the new class, which is important for the other functions.
