### ISSUE TITLE
Why is the color scale opposite to intuition?

### ISSUE THREAD

**Issue by holgerbrandl** [drsimonj/corrr#39]
For many people (including me) blue is associated with negative values and red with positives. This is for instance reflected in the temperature scale:
![](http://okfirst.mesonet.org/train/meteorology/graphics/Scale.gif)
![](http://www.earthonlinemedia.com/ebooks/tpe_3e/temperature/temp_scales_small_2.jpg)
![](http://www.ooshutup.com/wp-content/uploads/2015/08/temperature.gif)

Why is corrr using an opposite scale, where positive correlation is indicated by blue and negative correlation with red? Is it just coincidence or was it picked on purpose?

To support my argument the pals package for instance suggests a coolwarm scale as an efficient scale, going from blue (small/negative value) to red (high values). See https://cran.r-project.org/web/packages/pals/vignettes/pals_examples.html

Especially since the legend is not shown by default (which the wrong default imho), colors should match intuition.

**Comment by holgerbrandl** [comment]
A colleague of mine suggested to look into the existing literature, and positive correlation seems to be predominantly shown in red (which supports my argument). 
See yourself https://www.google.de/search?q=correlation+color+plot&source=lnms&tbm=isch&sa=X

**Comment by drsimonj** [comment]
Interesting question @holgerbrandl !

When it comes to temperature, I agree because it exactly reflects what we see around us (e.g., fire and ice). My choice was guided by a psychological sense that cool colours often represent 'positive' things and hot colours often represent 'negative' things, which I think is more appropriate for some non-physical thing like a correlation. So it's a colour scheme I've always used in this context.

However, I could be an outlier here, so an empirically-based decision is a good way to go! The link is useful, but I can see many using my colour scheme as well. To help us out, I've posted a survey on Twitter:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">How do you see colours for correlations?<br><br>Answer will affect default plot colours in corrr</p>&mdash; Simon Jackson (@drsimonj) <a href="https://twitter.com/drsimonj/status/826519647583232000">January 31, 2017</a></blockquote>

It will end in a couple of days and, hopefully, we'll have a nice idea of what people prefer :)

**Comment by holgerbrandl** [comment]
Thanks for the very constructive feedback. Doing a poll is a great idea. Though the deadline seems a little tight (until tomorrow only according to twitter).

**Comment by drsimonj** [comment]
Odd, I set it to two days. Anyway, tweets don't get much attention after a day or so. If the sample size is too small, I'll do another.

**Comment by drsimonj** [comment]
FYI, a colleague just reminded me that you might not be aware of ability to manually change colours. E.g., to reverse the colour order, you can do something like this:

```r
correlate(d) %>% network_plot(colours = c("skyblue1", "indianred2", "white"))
```

Also, I agree that legend should show by default. Will add this in soon (or feel free to submit a PR).

**Comment by holgerbrandl** [comment]
Thanks for the pointer, but I did know already that I can change the colors. I was curiously nevertheless about the motivation behind the default scale, that's why I created this ticket. 

So far the poll shows a clear bias towards the current color choice, but still ~30% seem to perceive the colors as I do. So showing the legend by default will definitely help those poor 30% to read corrr plots correctly.

**Comment by drsimonj** [comment]
Poll suggests keeping current colour orientation. But legend now set to TRUE by default :)
Thanks again.

**Comment by holgerbrandl** [comment]
Perfect, the poll suggested a 70-30 preference split (which I found very interesting by itself), so I think just adding the legend to the existing colors is the correct solution here. Thanks a lot for your help.

**Comment by drsimonj** [comment]
Yeah, very interesting result. I'm glad you prompted me to did it, as I could have been confusing ~30% of people!

**Comment by jkaupp** [comment]
Would this be addressed by adding a "reverse" option to the colour scale?

**Comment by drsimonj** [comment]
A "reverse" argument could be used, but I think it's too much for such a minor detail. The legend makes it pretty obvious, and people can reverse the colours by using the custom option shown above if they really want to.
