### ISSUE TITLE
Allow shave() to be called after fashion()?

### ISSUE THREAD

**Issue by jrosen48** [drsimonj/corrr#46]
Thanks for a great package. At this time, the following works:

```
mtcars %>% 
    dplyr::select(hp, wt, mpg) %>% 
    correlate() %>% 
    shave() %>% 
    fashion()
```

But changing the order of shave() and fashion():

```
mtcars %>% 
    dplyr::select(hp, wt, mpg) %>% 
    correlate() %>% 
    fashion() %>% 
    shave()
```

causes the following error to print:

    Error in UseMethod("shave") : 
      no applicable method for 'shave' applied to an object of class "c('data.frame', 'noquote')"

Would it be sensible to make a change to allow `shave()` to be called after `fashion()`?

**Comment by drsimonj** [comment]
Hi @jrosen48 and thanks for the feedback!

The quick answer: `fashion()` is for printing only, so it should always be the last function in a pipeline that you call.

To expand a little...
`fashion()` can be applied to almost any printable object, and thus can return structures other than correlation data frames. `fashion()` also converts all values to strings, so you can't do any normal work with the values after this conversion. You don't see `"` because they are printed as 'noquote' objects (done for aesthetic reasons). Given this, I wouldn't want someone to `fashion()` their correlations then try various computations and have trouble working out why they're getting errors.

**Comment by jrosen48** [comment]
Sounds sensible! Thank you for explaining.
