### ISSUE TITLE
rplot not working with plain tibbles

### ISSUE THREAD

**Issue by deann88** [drsimonj/corrr#49]
I find it odd that this code below is not working: 

> datasets::mtcars %>%
>        correlate() %>%
>        filter(mpg > .1) %>%
>        rplot
> 
> Error in UseMethod("rplot") : 
>   no applicable method for 'rplot' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

**Comment by drsimonj** [comment]
The issue is that once you use a dplyr function like `filter()` or `select()`, you can escape the standard square format of a correlation-matrix. E.g., in your example, notice that you drop the row corresponding to `"mpg"` altogether due to the diagonal value being `NA`. For this reason, the `cor_df` class gets dropped so as not to create conflicts with functions that depend on this expected format.

Furthermore, `rplot()` is intended for quick viewing, nothing too fancy. So you'll either need to maintain the `cor_df` structure (by replacing cells with `NA` where desired), or come up with a custom plot. E.g....

```r
library(corrr)
library(tidyverse)

datasets::mtcars %>%
  correlate() %>% # Create correlation data frame (cor_df)
  filter(mpg > .1) %>%
  gather(y, r, -rowname) %>% 
  ggplot(aes(rowname, y, size = r, color = r)) +
    geom_point()
```
